name: 'Telegram Bot Action'
description: 'A GitHub Action to send messages through Telegram Bot'
inputs:
  message:
    description: 'The message to be sent'
    required: true
  bot-token:
    description: 'Telegram bot token'
    required: true
  chat-id:
    description: 'Telegram chat ID'
    required: true
runs:
  using: 'node12'
  main: 'telegram.js'