name: Telegram Message Action
description: Envia un mensaje a Telegram
inputs:
  name:
    description: 'Name of the person to include in the message'
    required: true
  telegram_token:
    description: 'Telegram bot token'
    required: true
    
  telegram_chat_id:
    description: 'Telegram chat ID'
    required: true
    
runs:
  using: 'node12'
  main: 'telegram.js'