name: Readme modify
description: Modifica el readme
inputs:
  frase_positiva:
    description: 'Positive phrase to be displayed in the meme'
    required: true
  frase_negativa:
    description: 'Negative phrase to be displayed in the meme'
    required: true
  resultado_tests:
    description: 'Result of the tests execution'
    required: true

outputs:
  meme_addition:
    description: 'Confirmation message that the meme has been added to the README'

runs:
  using: 'node12'
  main: 'index.js'