name: main_workflow 
on: 
  push:
    branches:
      - nodejs_jest_job
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 10, 12 ]
   name: linter-execution
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       - name: Node ${{ matrix.node }} sample
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Linter execution
        uses:  github/super-linter@v4
        env: 
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  build1:
    needs: build
    name: test-execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest test
        run:
          npm install jest 
          npm test   
        
