name: main_workflow 
on: 
  push:
    branches:
      - nodejs_nodeversions_job
jobs:
  build:
    name: linter-execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with: 
            node-version: 10
      - name: Linter execution
        uses:  github/super-linter@v4
        env: 
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  build1:
    needs: build
    name: test-execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest test
        run:
          npm install jest 
          npm test   
        
