name: main_workflow 
on: 
  push:
    branches:
      - nodejs_nodeversions_job
jobs:
  build:
    name: linter-execution
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 10, 12 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with: 
            node-version: ${{ matrix.node }}
      - name: Linter execution
        uses:  github/super-linter@v4
        env: 
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  build1:
    needs: build
    name: test-execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest test
        run:
          npm install jest 
          npm test   
  build2:
    needs: build1
    name: environment_test_execution
    runs-on: ubuntu-latest
    steps:
      - name: hola
        uses: adeloyedeji/github-actions-hello@v1.0
        with:
            who-to-greet: 2DAW
        
