name: modify_readme
on: 
  push:
   branches:
    - github_action_readme
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: npm install jest && npm test
        working-directory: ./test
  modify-job:
    runs-on: ubuntu-latest
    if: always()
    needs: test-job
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions
        with:
          frase_positiva: "Los tests han funcionado/y lo sabes"
          frase_negativa: "Los tests han fallado.../y lo sabes"
          resultado_tests: ${{ needs.test-job.result }}
     