name: main_workflow 
on: 
  push:
    branches:
      - github_action_readme
jobs:
 
  build:
    needs: build
    name: test-execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest test
        run:
          npm install jest 
          npm test  
 
  add-meme:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add Meme to README
        uses: ./action
        with:
          frase_positiva: "Los tests han funcionado y lo sabes"
          frase_negativa: "Los tests han fallado y lo sabes"
          resultado_tests: ${{ job.status }}
      - name: Commit Changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -am "Add meme to README"
          git push
        
