name: Send Telegram Message

on:
  push:

jobs:
  envio_mensaje:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Enviar mensaje a Telegram
      uses: ./action
      