name: Send Telegram Message

on:
  push:

jobs:
  envio_mensaje:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Enviar mensaje a Telegram
      uses: ./action
      with:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_MESSAGE: "Hello from Github Actions2"
      