name: Send Telegram Message

on:
  push:
    branches:
      - send_telegram_action

jobs:
  envio_mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send Telegram Message
        uses: ./telegram.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        with:
          name: Javier