name: Send Telegram Message

on:
  push:

jobs:
  envio_mensaje:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Enviar mensaje a Telegram
      uses: ./.github/actions/telegram
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        NOMBRE: "Javier"